version: "3.9"

services:
  web:
    build: .
    container_name: pulsewatch_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
