name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

            - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host droplet
            HostName 142.93.7.69
            User root
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy to droplet
        run: |
          ssh droplet "
            cd /var/www/pulsewatch || mkdir -p /var/www/pulsewatch && cd /var/www/pulsewatch
            if [ ! -d .git ]; then
              git clone git@github.com:img0j0/pulsewatch.git .
            else
              git reset --hard
              git pull origin main
            fi
            docker compose down
            docker compose up -d --build
          "
